/*
 * Sources Internal
 *
 * Sources Internal
 *
 * API version: 2.0.0
 * Contact: support@redhat.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sourcesapiinternal

import (
	"encoding/json"
)

// AuthenticationExtra struct for AuthenticationExtra
type AuthenticationExtra struct {
	Azure *AuthenticationExtraAzure `json:"azure,omitempty"`
}

// NewAuthenticationExtra instantiates a new AuthenticationExtra object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthenticationExtra() *AuthenticationExtra {
	this := AuthenticationExtra{}
	return &this
}

// NewAuthenticationExtraWithDefaults instantiates a new AuthenticationExtra object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthenticationExtraWithDefaults() *AuthenticationExtra {
	this := AuthenticationExtra{}
	return &this
}

// GetAzure returns the Azure field value if set, zero value otherwise.
func (o *AuthenticationExtra) GetAzure() AuthenticationExtraAzure {
	if o == nil || o.Azure == nil {
		var ret AuthenticationExtraAzure
		return ret
	}
	return *o.Azure
}

// GetAzureOk returns a tuple with the Azure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticationExtra) GetAzureOk() (*AuthenticationExtraAzure, bool) {
	if o == nil || o.Azure == nil {
		return nil, false
	}
	return o.Azure, true
}

// HasAzure returns a boolean if a field has been set.
func (o *AuthenticationExtra) HasAzure() bool {
	if o != nil && o.Azure != nil {
		return true
	}

	return false
}

// SetAzure gets a reference to the given AuthenticationExtraAzure and assigns it to the Azure field.
func (o *AuthenticationExtra) SetAzure(v AuthenticationExtraAzure) {
	o.Azure = &v
}

func (o AuthenticationExtra) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Azure != nil {
		toSerialize["azure"] = o.Azure
	}
	return json.Marshal(toSerialize)
}

type NullableAuthenticationExtra struct {
	value *AuthenticationExtra
	isSet bool
}

func (v NullableAuthenticationExtra) Get() *AuthenticationExtra {
	return v.value
}

func (v *NullableAuthenticationExtra) Set(val *AuthenticationExtra) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthenticationExtra) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthenticationExtra) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthenticationExtra(val *AuthenticationExtra) *NullableAuthenticationExtra {
	return &NullableAuthenticationExtra{value: val, isSet: true}
}

func (v NullableAuthenticationExtra) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthenticationExtra) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


