/*
 * Sources Internal
 *
 * Sources Internal
 *
 * API version: 2.0.0
 * Contact: support@redhat.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sourcesapiinternal

import (
	"encoding/json"
)

// CollectionMetadata struct for CollectionMetadata
type CollectionMetadata struct {
	Count *int32 `json:"count,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
}

// NewCollectionMetadata instantiates a new CollectionMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCollectionMetadata() *CollectionMetadata {
	this := CollectionMetadata{}
	return &this
}

// NewCollectionMetadataWithDefaults instantiates a new CollectionMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCollectionMetadataWithDefaults() *CollectionMetadata {
	this := CollectionMetadata{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *CollectionMetadata) GetCount() int32 {
	if o == nil || o.Count == nil {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionMetadata) GetCountOk() (*int32, bool) {
	if o == nil || o.Count == nil {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *CollectionMetadata) HasCount() bool {
	if o != nil && o.Count != nil {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *CollectionMetadata) SetCount(v int32) {
	o.Count = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *CollectionMetadata) GetLimit() int32 {
	if o == nil || o.Limit == nil {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionMetadata) GetLimitOk() (*int32, bool) {
	if o == nil || o.Limit == nil {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *CollectionMetadata) HasLimit() bool {
	if o != nil && o.Limit != nil {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *CollectionMetadata) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *CollectionMetadata) GetOffset() int32 {
	if o == nil || o.Offset == nil {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionMetadata) GetOffsetOk() (*int32, bool) {
	if o == nil || o.Offset == nil {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *CollectionMetadata) HasOffset() bool {
	if o != nil && o.Offset != nil {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *CollectionMetadata) SetOffset(v int32) {
	o.Offset = &v
}

func (o CollectionMetadata) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Count != nil {
		toSerialize["count"] = o.Count
	}
	if o.Limit != nil {
		toSerialize["limit"] = o.Limit
	}
	if o.Offset != nil {
		toSerialize["offset"] = o.Offset
	}
	return json.Marshal(toSerialize)
}

type NullableCollectionMetadata struct {
	value *CollectionMetadata
	isSet bool
}

func (v NullableCollectionMetadata) Get() *CollectionMetadata {
	return v.value
}

func (v *NullableCollectionMetadata) Set(val *CollectionMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableCollectionMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableCollectionMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollectionMetadata(val *CollectionMetadata) *NullableCollectionMetadata {
	return &NullableCollectionMetadata{value: val, isSet: true}
}

func (v NullableCollectionMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollectionMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


