/*
 * Sources Internal
 *
 * Sources Internal
 *
 * API version: 2.0.0
 * Contact: support@redhat.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sourcesapiinternal

import (
	"encoding/json"
)

// ErrorNotFoundErrors struct for ErrorNotFoundErrors
type ErrorNotFoundErrors struct {
	Status *string `json:"status,omitempty"`
	Detail *string `json:"detail,omitempty"`
}

// NewErrorNotFoundErrors instantiates a new ErrorNotFoundErrors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorNotFoundErrors() *ErrorNotFoundErrors {
	this := ErrorNotFoundErrors{}
	return &this
}

// NewErrorNotFoundErrorsWithDefaults instantiates a new ErrorNotFoundErrors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorNotFoundErrorsWithDefaults() *ErrorNotFoundErrors {
	this := ErrorNotFoundErrors{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ErrorNotFoundErrors) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorNotFoundErrors) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ErrorNotFoundErrors) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ErrorNotFoundErrors) SetStatus(v string) {
	o.Status = &v
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *ErrorNotFoundErrors) GetDetail() string {
	if o == nil || o.Detail == nil {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorNotFoundErrors) GetDetailOk() (*string, bool) {
	if o == nil || o.Detail == nil {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *ErrorNotFoundErrors) HasDetail() bool {
	if o != nil && o.Detail != nil {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *ErrorNotFoundErrors) SetDetail(v string) {
	o.Detail = &v
}

func (o ErrorNotFoundErrors) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Detail != nil {
		toSerialize["detail"] = o.Detail
	}
	return json.Marshal(toSerialize)
}

type NullableErrorNotFoundErrors struct {
	value *ErrorNotFoundErrors
	isSet bool
}

func (v NullableErrorNotFoundErrors) Get() *ErrorNotFoundErrors {
	return v.value
}

func (v *NullableErrorNotFoundErrors) Set(val *ErrorNotFoundErrors) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorNotFoundErrors) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorNotFoundErrors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorNotFoundErrors(val *ErrorNotFoundErrors) *NullableErrorNotFoundErrors {
	return &NullableErrorNotFoundErrors{value: val, isSet: true}
}

func (v NullableErrorNotFoundErrors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorNotFoundErrors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


